// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq1Dijda4UTM6pLnLf39yf1X8Kshx_j5U',
    appId: '1:598629656855:web:4a19093e80519a2a202f52',
    messagingSenderId: '598629656855',
    projectId: 'helpinghands-8f043',
    authDomain: 'helpinghands-8f043.firebaseapp.com',
    storageBucket: 'helpinghands-8f043.appspot.com',
    measurementId: 'G-XJ6SD51889',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVgNhtgYpMkmqJ-XiB7N8ic4-y16wzbOA',
    appId: '1:598629656855:android:e06c5134f7bb9b9f202f52',
    messagingSenderId: '598629656855',
    projectId: 'helpinghands-8f043',
    storageBucket: 'helpinghands-8f043.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwrKZGVa18EhTUplb_eMqJ7WHr64GmPOo',
    appId: '1:598629656855:ios:24f4948e0d667673202f52',
    messagingSenderId: '598629656855',
    projectId: 'helpinghands-8f043',
    storageBucket: 'helpinghands-8f043.appspot.com',
    iosClientId: '598629656855-8ksnb64b5i49puqnuq1gmujnp7otmute.apps.googleusercontent.com',
    iosBundleId: 'com.example.monkeyAppDemo',
  );
}
